# Generated by Django 3.0.5 on 2020-04-25 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200426_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 1, 18, 20, 163587), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='tutorialcategory',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='main/images'),
        ),
    ]
